### ISSUE TITLE
[5th beta release] Scanning starts and finish immediately, doing nothing 

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#110]
Using Linux.
```
$ sudo archlinux-java get
java-16-openjdk
```

Clicking on "Scan" button leads to nothing.
DAT is from `mame -listxml` (M. A. M. E. 0.235).
DAT is correctly (I suppose) parsed and loaded.

log:
```
[2021-09-09 19:10:06] [FINE] file=/home/myuser/.jrommanager/xmlfiles/mame0235.xml.properties, propsize=19
[2021-09-09 19:10:06] [FINE] before store
[2021-09-09 19:10:06] [FINE] stored
```
No errors printed out on terminal.

Reverting back to 4th beta release for now (works like a charm).

**Comment by optyfr** [comment]
Could you empty `/home/myuser/.jrommanager/cache/` directory then retry?
Are source and destinations paths printing okey in the interface?
were you using the swing gui or one of the web servers?

**Comment by cinnamonmatexfce** [comment]
> Could you empty `/home/myuser/.jrommanager/cache/` directory then retry?
> Are source and destinations paths printing okey in the interface?
> were you using the swing gui or one of the web servers?
> 

Cleaning the cache leads to same problem.
I also tried wiping out the whole directory, but nothing. 
Yup, paths are printed OK.
I always used GUI only.

**Comment by optyfr** [comment]
ok, how did you install this version? from an available binary package in github's release? from sources using gradle? other?
Just to be sure to test the same thing this week-end...

**Comment by cinnamonmatexfce** [comment]
> ok, how did you install this version? from an available binary package in github's release? from sources using gradle? other?
> Just to be sure to test the same thing this week-end...

Installed modifying the version in [PKGBUILD](https://aur.archlinux.org/packages/jrommanager-bin/)

**Comment by optyfr** [comment]
Successfully scanned 0.235 with https://github.com/optyfr/JRomManager/releases/download/2.5.0-beta.5/jrommanager_2.5.0-1_amd64.deb on Debian 11 not sure if I will have time to try with ArchLinux (I have one... but headless)
BTW this .deb package contains a bundled JDK 11
Maybe that JDK 16 is a problematic one? fyi I will switch directly to Java 17 as a requirement for 2.6.x, but currently it's compiled using JDK 11 but should theoretically work for JDK >11
I'll eventually try the all.deb package without jdk bundled and system's JDK 17 (JDK 16 is not available on debian 11)

**Comment by optyfr** [comment]
the all.deb is ok too, even with openjdk-17-jre
will try now the https://github.com/optyfr/JRomManager/releases/download/2.5.0-beta.5/JRomManager-2.5.0.zip version, this is the one that your PKGBUILD is supposed to download

**Comment by optyfr** [comment]
worked too...
Could you export and attach here your settings file? (use "Export Settings" button)

**Comment by cinnamonmatexfce** [comment]
> worked too...
> Could you export and attach here your settings file? (use "Export Settings" button)

Same settings I use in 4th beta.

Here's to you:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<entry key="backup">false</entry>
<entry key="filter.InclDisks">true</entry>
<entry key="disks_dest_dir">/mnt/mymountHDD/mame/latest/latest_roms</entry>
<entry key="use_parallelism">true</entry>
<entry key="disks_dest_dir_enabled">true</entry>
<entry key="format">ZIP</entry>
<entry key="automation.scan">SCAN</entry>
<entry key="hash_collision_mode">SINGLEFILE</entry>
<entry key="filter.DriverStatus">preliminary</entry>
<entry key="samples_dest_dir">/mnt/mymountHDD/mame/latest/latest_samples</entry>
<entry key="filter.YearMax">????</entry>
<entry key="roms_dest_dir">/mnt/mymountHDD/mame/latest/latest_roms</entry>
<entry key="create_mode">true</entry>
<entry key="filter.YearMin"></entry>
<entry key="samples_dest_dir_enabled">true</entry>
<entry key="filter.InclClones">true</entry>
<entry key="implicit_merge">true</entry>
<entry key="merge_mode">SUPERFULLNOMERGE</entry>
</properties>
```

`latest_roms` contains zipped roms and chds in their relative folders.
`latest_samples` contains zipped samples

**Comment by optyfr** [comment]
no src_dirs ? at least one src_dir is required, even if empty, but it should have been at least logged if not present...

**Comment by cinnamonmatexfce** [comment]
> no src_dirs ? at least one src_dir is required, even if empty, but it should have been at least logged if not present...

I was only to check my romset, it's complete already. The problem appears also when/if setting `src` dir(s).

**Comment by optyfr** [comment]
> I was only to check my romset, it's complete already. The problem appears also when/if setting `src` dir(s).

indeed...

**Comment by optyfr** [comment]
Seems to be a problem with samples dir...

**Comment by cinnamonmatexfce** [comment]
> Seems to be a problem with samples dir...

yup, deselecting `samples` made Scan to start
