### ISSUE TITLE
customizable global [backup] path

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#118]
Hey @optyfr could be easily done adding support for customizing `backup` path globally (NOT(per-profile))?

Thanks

**Comment by optyfr** [comment]
Yes probably, it should be feasible, but please keep in mind that the purpose of that backup is not only to restore lost roms, but also to retrieve unexpected roms between profiles, so setting the backup differently per profile will circumvent that purpose

**Comment by cinnamonmatexfce** [comment]
> also to retrieve unexpected roms between profiles

Good point indeed.
So, maybe just setting a single custom global path would be fine

**Comment by optyfr** [comment]
I'll offer the two possibilities : first per profile, and if not defined per profile, global settings will used, but if the last one is not set, then it will be %work/backup as usual
Furthermore, if set per profile, scan will always be done per profile *then* global backup setting *and finally* the hard coded path
Currently, until it's done, you could use [bind mount](https://unix.stackexchange.com/questions/198590/what-is-a-bind-mount) or [symbolic link](https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/)

**Comment by cinnamonmatexfce** [comment]
Many many thanks @optyfr!! 


> Currently, until it's done, you could use [bind mount](https://unix.stackexchange.com/questions/198590/what-is-a-bind-mount) or [symbolic link](https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/)

Yup, I'm already using bind mount, 'cause I don't have huge space available on my `/home` partition ;)
