### ISSUE TITLE
AppImage Support

### ISSUE THREAD

**Issue by shakeyourbunny** [optyfr/JRomManager#128]
Would you be so kind and provide an AppImage for your utility for easier deployment?

AppImages are also something you create and you have covered 100% linux support across all distributions.

See https://appimage.org/

**Comment by optyfr** [comment]
What's the difference with flathub packages? [The update to 2.5.0 is in preparation for flathub](https://github.com/flathub/com.github.optyfr.JRomManager/pull/11)

**Comment by shakeyourbunny** [comment]
Both formats bring all their dependencies with them, but the most striking difference is that the Flathub is a distribution-neutral package system (which requires a special daemon to take care of it) and the Appimage format is that you have one file where everything for the application is in it, you can put it everywhere and just run it. Internally, it mounts itself als a loop device and runs a pre-defined executable which bootstraps the application.

In my case, I use SuSE Tumbleweed, and although you provide RPMs, their are only usable with the RedHat/Fedora/CentOS family, which SuSe is not part of, so the filesystem layout and the dependencies provided by the RPM package are different and thus unusable for me. 

Also, you do not provide repository information and I want to have my updates of applications neatly managed and want to avoid Flathub. Perhaps you look into the SuSE buildbot services on https://build.opensuse.org/, where you can host your builds alongside autogenerated repositories? This service is not only for SuSE distributions, but also provide support for all major Linux distributions. Major advantage of using this is that you can provide repos for all distributions and enable proper integration into the respective update system (apt, yum, dnf, zypper, you name it).

SuSE (tumbleweed) does provide flathub support, but I prefer to collect my third-party application in a folder for easier and isolated management of foreign, non-repository applications.

**Comment by optyfr** [comment]
OK, I understand the reason and motivation
I need to see the feasibility with GitHub Actions...

**Comment by cinnamonmatexfce** [comment]
Hey @optyfr can you also please update AUR packages (I think it's not worth opening a separate issue...). Both `src` and `bin` PKGBUILDS... Thanks ;)

**Comment by optyfr** [comment]
@cinnamonmatexfce need to check if my arch still boot
@shakeyourbunny any clue on how to make an appimage which support 4 alternatives executable (swing, server, fullserver, cli)?

**Comment by optyfr** [comment]
@cinnamonmatexfce could you check the updated AUR packages please?

**Comment by cinnamonmatexfce** [comment]
> @cinnamonmatexfce could you check the updated AUR packages please?

(not) Everything's fine! Many many thanks @optyfr! ;)

`src` package from AUR is failing (`-bin` is OK)

See: #131

**Comment by optyfr** [comment]
@shakeyourbunny there is now an appimage in the 2.5.0 release assets... it was :
- manually built, 
- only tested on Debian 11,
- support only swing mode

Please let me know if it works for you

**Comment by cinnamonmatexfce** [comment]
> @shakeyourbunny there is now an appimage in the 2.5.0 release assets... it was :
> 
>     * manually built,
> 
>     * only tested on Debian 11,
> 
>     * support only swing mode
> 
> 
> Please let me know if it works for you

Latest ArchLinux: no problems so far...
The AppImage starts correctly and JRomManager works fine reading its files from `$HOME/.jromanager` (please note that the folder is pre-existing as it was previously created by other uses of JRomManager installed via sources from ArchLinux AUR).

**Comment by shakeyourbunny** [comment]
Currently, my Linux computer cannot boot due defective graphics card which is currently processed by a warranty case (luckily), I'm typing that on an old Windows box, but will test it as soon as I got my graphics card replacement.

**Comment by optyfr** [comment]
@shakeyourbunny ok, I'll keep open this issue until you are able to test it. 
BTW, I found a way to use multiple alternative executables from a single appimage : if you create a symbolic link to this AppImage named either JRomManagerFullServer, JRomManagerServer, or JRomManagerCLI... It'll be internally recognized and the right executable will be used (and of course all args according the chosen exec)

**Comment by shakeyourbunny** [comment]
Hi,

my computer got repaired and got my SuSE Tumbleweed. It works fine!

**Comment by optyfr** [comment]
Ok thanks
