### ISSUE TITLE
ArchLinux src AUR build fails

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#131]
Attaching console output [JRomManager AUR src fails.log](https://github.com/optyfr/JRomManager/files/7448391/JRomManager.AUR.src.fails.log)

```
$ archlinux-java status
Available Java environments:
  java-11-openjdk
  java-17-openjdk (default)
  java-8-openjdk/jre
```

```
$ archlinux-java get
java-17-openjdk
```

**Comment by optyfr** [comment]
jdk 11 is mandatory to build, it's specified in PKGBUILD via the line `makedepends=('java-environment=11')` so why it does not take it into account?
`archlinux-java set java-11-openjdk` prior `makepkg` solve temporarily the problem

**Comment by optyfr** [comment]
Seems that it downloads the right jdk, but stupidly does not set any JAVA_HOME env variable according to this jdk...
So I added `JAVA_HOME=/usr/lib/jvm/java-11-openjdk` in the line call to gradlew inside PKGBUILD
Please let me know if it solves the problem
