### ISSUE TITLE
Index 5076 out of bounds for length 5076

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#135]
![JRomManager_Scanner_Index_error](https://user-images.githubusercontent.com/65762930/141363522-26d3d52a-8dee-4aa4-8abf-da42ef04f661.jpg)

At the end of _Scanning_, when _Saving cache..._ it throws out the error.
There is no output in Bash.

I'm using this modded launcher:
```
#!/bin/sh
cd /usr/share/java/jrommanager
OPT=-Xmx8g
which grep >/dev/null
if [ $? -eq 0 ]; then
        which file >/dev/null
        if [ $? -eq 0 ]; then
                file -L $(which java) | grep -q '64-bit'
                if [ $? -eq 0 ]; then OPT=-Xmx16g; fi
        else
                java --version | grep -q '64-Bit'
                if [ $? -eq 0 ]; then OPT=-xmx16g; fi
        fi
fi
java $OPT -jar JRomManager.jar --multiuser --noupdate&
```

Next try is done with original launcher, I got _Index 5082 out of bounds for length 5082_ this time.

Noteworthy _Settings_ changes:
- _Scanner / Settings / Enable MultiThreading_ : YES
- _Scanner / Settings / Compression_ : TorrentZip archive
- _Scanner / Settings / Merge Mode_ : Non Merged (including BIOS and Devices)
- _Settings / General / Threading_ : Max available [Ryzen 7 1700]
- _Settings / Compressors / 7z (external) / Threads_ : 1 [default would be **-1**]
- _Settings / Compressors / 7z (external) / Solid archive_ : NO [default would be **YES**]

Sources are all NFS folders.
Destination is a directory inside a NTFS mounted partition:
```
UUID=blahblahblah   /mnt/ntfs/somepath      ntfs    rw,nosuid,nodev,uid=1000,gid=1000,dmask=022,fmask=133,allow_other,big_writes,windows_names,relatime,owner,user,exec     0 0
```

This is the DAT / XML I'm using: https://github.com/libretro/mame2003-plus-libretro/blob/master/metadata/mame2003-plus.xml

_JRM.0.log_:
```
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/frogs.zip : zip END header not found
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/invaders.zip : zip END header not found
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/omegrace.zip : zip END header not found
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/warrior.zip : zip END header not found
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/solarq.zip : zip END header not found
[2021-11-11 21:16:14] [SEVERE] /path/to/source/dirs/mame2003plus/system/mame2003-plus/artwork/skydiver.zip : zip END header not found
[2021-11-11 21:16:29] [SEVERE] /path/to/source/dirs/2000/Roms/kungfum.zip : zip END header not found
[2021-11-11 21:16:29] [SEVERE] /path/to/source/dirs/2000/Roms/kingbalj.zip : zip END header not found
[2021-11-11 21:16:29] [SEVERE] /path/to/source/dirs/2000/Roms/blockade.zip : zip END header not found
[2021-11-11 21:16:46] [SEVERE] Index 5082 out of bounds for length 5082
java.lang.ArrayIndexOutOfBoundsException: Index 5082 out of bounds for length 5082
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:972)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1049)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at jrm.profile.scan.Scan.<init>(Scan.java:336)
	at jrm.profile.scan.Scan.<init>(Scan.java:229)
	at jrm.ui.ScannerPanel$1.doInBackground(ScannerPanel.java:258)
	at jrm.ui.ScannerPanel$1.doInBackground(ScannerPanel.java:253)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by optyfr** [comment]
Well... I would say that there is a serious bug in the jdk version that you're using!!! this bug arise when converting HashMap values to an ArrayList, and this conversion happens on torrentzip actions (after having saved the cache)
In case you wonder, I doubt that this is related to the corrupted zip files in the log
What is you current JDK/JRE (seems it's not JDK 11)?
Please also note that setting Solid Archive to NO for 7z will disrespect compression level, it's a bug in sevenzipjbinding library

**Comment by cinnamonmatexfce** [comment]
I'm using `extra/jre-openjdk 17.u35-1` which is default in latest ArchLinux.
I'll do some tests with `extra/jre11-openjdk 11.0.12.u7-1`.
Furthermore I'm having some headaches scanning PS1 games (`7z`, `rar`, `zip`) and compressing 'em in 7z, but I'll do some tests with Java 11 before opening issues.

----------------------------
P. S.: how are threads calculated and related between _(General) Threading_ **and** _(7z) Threads_? Hypothetically setting 16 cores **and** 16 7z threads I'll end up with 16^2 threads?

**Comment by cinnamonmatexfce** [comment]
> Well... I would say that there is a serious bug in the jdk version that you're using!!! this bug arise when converting HashMap values to an ArrayList, and this conversion happens on torrentzip actions (after having saved the cache) 

You're right. Confirmed all OK with Java 11. Closing because it's solved (BUG is in Java 17).



> In case you wonder, I doubt that this is related to the corrupted zip files in the log What is you current JDK/JRE (seems it's not JDK 11)? 

Yup: _Fix_ operation went fine, despite corrupted files. Closing.

**Comment by optyfr** [comment]
> Furthermore I'm having some headaches scanning PS1 games (`7z`, `rar`, `zip`) and compressing 'em in 7z, but I'll do some tests with Java 11 before opening issues.

Be careful with 7z, you can rapidly exhaust all your memory and finish into swap, especially with high compression levels, furthermore with native libraries this can crash JRM because it's out of the JVM exception handling
 
> P. S.: how are threads calculated and related between _(General) Threading_ **and** _(7z) Threads_? Hypothetically setting 16 cores **and** 16 7z threads I'll end up with 16^2 threads?

Yes indeed it's 16^2 at some point in time, I would recommend setting only 1 or 2 threads for 7z, balancing depends mainly of your disk speed and how hard you compress, theoretically more threads to 7z and less to JRM if your disks are slow

**Comment by optyfr** [comment]
> > Well... I would say that there is a serious bug in the jdk version that you're using!!! this bug arise when converting HashMap values to an ArrayList, and this conversion happens on torrentzip actions (after having saved the cache)
> 
> You're right. Confirmed all OK with Java 11. Closing because it's solved (BUG is in Java 17).

It's quite annoying anyway, I'll do some extra checks...

**Comment by cinnamonmatexfce** [comment]
> > Furthermore I'm having some headaches scanning PS1 games (`7z`, `rar`, `zip`) and compressing 'em in 7z, but I'll do some tests with Java 11 before opening issues.
> 
> Be careful with 7z, you can rapidly exhaust all your memory and finish into swap, especially with high compression levels, furthermore with native libraries this can crash JRM because it's out of the JVM exception handling
>  

As you suggested me some time ago, I modded the executable in `/usr/bin` to let JRomManager gain access to more RAM (I have a toral of 16GB installed). My hard disk setup is RAID0 (`ext4`) with 7200rpm mechanical drives via a NFS server (1Gbps ethernet).

**Comment by cinnamonmatexfce** [comment]
> 
> Furthermore I'm having some headaches scanning PS1 games (`7z`, `rar`, `zip`) and compressing 'em in 7z, but I'll do some tests with Java 11 before opening issues.
> 


Please have a look at #137

**Comment by optyfr** [comment]
This is not really a jdk bug but a synchronization issue, map is filled from many threads (when multi threading is activated), this worked fine until jdk 11 despite missing synchronized keywords, but HashMap class were reworked since jdk 15 and now it always fails, synchronizing list and map at creation will resolve the problem for jdk 15/16/17 and more
This synchronization fix may resolve some inexplicable problems that were silently failing under jdk 11

**Comment by optyfr** [comment]
commit 9a761bf2ad5f789edd17655bb07d91352f5a2001 resolve this issue
