### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by taalas** [optyfr/JRomManager#142]
Hi,

I am not sure how feasible this is, but have you considered providing an official docker image for this project? I imagine it being very well suited to run directly on a NAS system holding the files e.g.

**Comment by optyfr** [comment]
Seems that it concerns the web server mode, isn't it?

**Comment by taalas** [comment]
Exactly. I know that JDownloader2 is doing something similar in docker. It exposes the web server gui to the user. Maybe something similar could be applied here?

**Comment by optyfr** [comment]
yes should be feasible, in fact a lot of docker services are written in java, for example : sonarqube, jenkins, ...

**Comment by taalas** [comment]
Anything I can do to help with this?

**Comment by optyfr** [comment]
Not sure, I need time, and currently I started entire rewrite into javafx for the desktop interface, so this need to be finished first

**Comment by taalas** [comment]
Sure, I understand. Just for the sake of completeness here is the base image JDownloader2 uses to expose the GUI:
https://github.com/jlesage/docker-baseimage-gui

**Comment by optyfr** [comment]
Thanks but the purpose is not the same, this docker image is for displaying graphical apps inside a web browser using vnc… whereas JRomManager as already a complete web client and can work headless without tricks 
Anyway it’s good to know that it’s also possible to run desktop apps through docker

**Comment by AROAH1337** [comment]
All one would need to do is create a Dockerfile that essentially just runs the commands required to configure a basic installation from scratch. I'll add this to my list of projects in case no one else gets to it in the meantime.

**Comment by optyfr** [comment]
While a Dockerfile would be enough to just say : "Hey! JRomManager can run with docker!", but since the purpose is to do an "Official Docker image", the main challenge here is to publish a docker image into the docker hub automatically from github actions each time there is release tag event

**Comment by optyfr** [comment]
Please see https://hub.docker.com/r/optyfr/jrommanager
