### ISSUE TITLE
Allow Forcing External 7-Zip Compressor

### ISSUE THREAD

**Issue by RibShark** [optyfr/JRomManager#143]
Currently if SevenZipJBinding is available, JRomManager will use that regardless of if you have an external compressor set. I would like to be able to use an external 7-Zip executable in order to be able to use the STORE method, so that I can later run any created archives through torrent7z. SevenZipJBinding currently uses LZMA2 which torrent7z cannot uncompress, which makes converting the archives very time consuming.

(Support for using an external t7z executable directly would be great too :P)

**Comment by cinnamonmatexfce** [comment]
You're talking about two-steps compression: 1st one with JRomManager and 2nd one with torrent7z, so... Why not to initially create folders sets in JRomManager and then compress these folders into your preferred format?

**Comment by optyfr** [comment]
... or use STORE compression level settings with SevenZipJBinding (solid mode should be kept anyway if I remember)

**Comment by RibShark** [comment]
> ... or use STORE compression level settings with SevenZipJBinding (solid mode should be kept anyway if I remember)

There doesn't appear to be a way to set this, there is no 7z (internal) tab and setting the option on the external tab does not make SevenZipJBinding use STORE.
![image](https://user-images.githubusercontent.com/1957489/144290521-86d6b9be-cc2b-462f-9280-85b13daa0078.png)

**Comment by RibShark** [comment]
> You're talking about two-steps compression: 1st one with JRomManager and 2nd one with torrent7z, so... Why not to initially create folders sets in JRomManager and then compress these folders into your preferred format?

Because my existing sets are already t7zipped, I do not want to have to recompress the entire set every time I add a new game to it.

**Comment by optyfr** [comment]
Check also solid mode, the « ext » should apply only for command line

**Comment by optyfr** [comment]
It's been verified, checking solid mode + selecting STORE compression level under "7z (ext)" tab, will generate 7z with store mode even  when using SevenZipJBinding
