### ISSUE TITLE
Fix doesn't compress all files with 7zip

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#145]
I want to compress a Rom set and have chosen 7zip to do so.
When I click on fix after scanning, only 3 files are being compressed and then the progression window closes.
After that I can click fix again and the next 3 files are being compressed. It just doesn't proceed automatically ...

**Comment by optyfr** [comment]
What release was used?
Which 7zip options was used (external or internal, compression level, solid mode, etc...) ?
Can you attach the log file here please?

**Comment by SpaceAgeHero** [comment]
![image](https://user-images.githubusercontent.com/949727/146745093-0c584842-8321-45df-9532-22f5b7593b94.png)
[JRM.0.log](https://github.com/optyfr/JRomManager/files/7744172/JRM.0.log)

Sure, sorry. Threads was default: -1 with the same issue.

Version 2.5.0 from AUR

**Comment by optyfr** [comment]
The fix is stopping because you're running out of space in /tmp
`java.nio.file.FileSystemException: /run/media/SpaceAgeHero/GAMES/PSPsrc/Syphon Filter - Logan's Shadow (Europe) (En,Fr,De,Es,It,Pl,Ru).iso -> /tmp/JRM825153648768349390/Syphon Filter - Logan's Shadow (Europe) (En,Fr,De,Es,It,Pl,Ru).iso: No space left on device
`
please see issue #138

**Comment by optyfr** [comment]
btw I realized that I did not update to 2.5.1 for archlinux... hope to do that in a few hours

**Comment by SpaceAgeHero** [comment]
Can I specify a different temp path? Don't want to mess with Arch's default /tmp space allocation as I never had issues with other applications.

**Comment by optyfr** [comment]
you can eventually tune java call by starting using this extra arg 
-Djava.io.tmpdir=your_new_dir
or also see if your /tmp is not full of old files
but surely other applications does not compress more than one iso file at a time too, so you can also tune or disable multi-threading (not the one from 7zip)
btw, /tmp with less than 4G free is a nonsense nowadays...

**Comment by SpaceAgeHero** [comment]
My /tmp dir has 8GB available space, but of course even that can become insufficient when compressing optical media based images with 8+ tasks.
I'd like to request a setting right in the program to specify a temp path, if possible.

**Comment by optyfr** [comment]
You have to know that halves of the temp dir usage are not under my control (ie: from libraries), and changing default temp dir 
 after program start is a real potential problem as specified from javadoc :
`The default temporary-file directory is specified by the system property java.io.tmpdir. On UNIX systems the default value of this property is typically "/tmp" or "/var/tmp"; on Microsoft Windows systems it is typically "C:\\WINNT\\TEMP". A different value may be given to this system property when the Java virtual machine is invoked, but programmatic changes to this property are not guaranteed to have any effect upon the temporary directory used by this method.`
So as you can read there is no guarantee to work as expected, somes already got troubles with that, so there is only 3 solutions for you (from most to least recommended) :

1. resize your partitions with a gparted live or with lvm (if lvm was used)
2. specify the java.io.tmpdir system property at java call
3. reduce the number of simultaneous tasks until it fits your temp dir

**Comment by cinnamonmatexfce** [comment]
> btw I realized that I did not update to 2.5.1 for archlinux... hope to do that in a few hours

Not a big deal since during install one can modify `PKGBUILD` "on-the-fly" and point to latest release... But if you can update the package in AUR, well... Thank you!! ;)

**Comment by cinnamonmatexfce** [comment]
> Can I specify a different temp path? Don't want to mess with Arch's default /tmp space allocation as I never had issues with other applications.

Yup. Also I did't want to change default behaviour of ArchLinux `/tmp` (although it is safely doable).

I suggest you to go and find out your best compromise doing some tests to get the good tradeoff between JRomManager threads VS 7z threads VS 7z Compression Method...


Anyway...
Have you considered creating uncompressed folder sets and then proceeding with the compression jobs using `7z` with `parallel`?
I find out you'll get higher compression ratios and more threads at once.
