### ISSUE TITLE
Ignore Specific Files/Folders

### ISSUE THREAD

**Issue by PhasecoreX** [optyfr/JRomManager#146]
I see that there is the "Ignore Unknown Containers" option for scanner settings, however I was wondering if there could be an option to ignore specific file/folder patterns. I still want to detect if there are extraneous files, but only if they aren't specific ones I want to allow.

For example, fbneo makes a folder called "fbneo" in the roms folder which stores all the high score and nvram files. Another example, if I was using JRomManager to manage my other systems, is that RetroArch/Lakka stores the cores save files into the roms folder, as an *.srm file.

So, I'd want to ignore specific folders/files, as well as files that end with a specific extension. If that's already possible, I must have missed it, otherwise I guess this is a feature request.

Excellent work so far on JRomManager! I look forward to dropping the other rom managers in favor of this one, since it works on Linux so nicely.

**Comment by optyfr** [comment]
I understand your problem, and indeed there is currently no way to do this in jrm, so it's a feature request that could be feasible... but before going further, my first question is : at what point the pattern have to be complex to fit all these cases? This can go from only glob pattern type up to complex regex pattern needs, it may depend if the dat/xml is global or per machine/core

I think you will love the next version (3.0) with a new gui based on JavaFX...

**Comment by PhasecoreX** [comment]
At the moment, I think glob patterns would cover my use cases: `fbneo/`, `readme.txt`, and `*.srm`, assuming the `fbneo/` excludes that folder as well as anything inside of it. I can't imagine a scenario where a user has a bunch of files they want ignored that would be more convenient to use a regex on. My assumption is that there would be an extra folder if the emulator stores custom data in it (fbneo, duckstation, mupen64plus), and files with specific extensions, such as save states, save files, boxart, video previews, per-rom overrides, etc. This is from a Lakka and RetroPie standpoint, and how they store files.

And these ignores would be per profile, as some romsets emulators use srm files while others use mcd files, for example.

Thank you for the enhancement consideration! And yes, version 3 sounds like it'll be really nice, excited to see it!

**Comment by optyfr** [comment]
done in 2433d28d4da06f9ec8e5d57f72a2e29cc505ae52
