### ISSUE TITLE
How to open the .app on macOS

### ISSUE THREAD

**Issue by cplr** [optyfr/JRomManager#154]
Seems like there's a bug in Java, documented here: https://bugs.openjdk.java.net/browse/JDK-8276150

If anyone is having an issue opening the app on macOS, you need to run in Terminal:

`sudo xattr -cr JRomManager.app`

Noting this here in case anyone else comes across the problem. Might be worth adding to the README.

**Comment by optyfr** [comment]
The bug has been fixed in java 17.0.5, and because we use 17.0.6 since a few releases, it should then be hopefully fixed...
