### ISSUE TITLE
Question regarding dir2dat

### ISSUE THREAD

**Issue by docbobo** [optyfr/JRomManager#172]
II was looking at the Dir2Dat functionality and failed to create a DAT File. Comparing the documentation with the current build, the screenshots seem to suggest that the DstDat field  should be point to a DAT File, not a Directory. However, the field cannot be edit manually and the chooser dialog is for a directory (https://github.com/optyfr/JRomManager/blob/962fcf364935bd3808fa9aa161ce8c7901e6f740/JRomManager/src-jfx/jrm/fx/ui/Dir2DatController.java#L94)

Am I doing something wrong here?

**Comment by optyfr** [comment]
You are currently looking at the java-fx code of the next 3.0 version... which is indeed wrong
You should look at [2.5 branch](https://github.com/optyfr/JRomManager/tree/2.5) and for swing version [here](https://github.com/optyfr/JRomManager/blob/2e5bceafeb7da924c9fd3a86ecced5a10050b580/JRomManager/src-standalone/jrm/ui/Dir2DatPanel.java#L446) which is requesting a file
But as I know that you are looking for the web version then it's [there](https://github.com/optyfr/JRomManager-WebClient/blob/8dd72b9def004ce432b460357ebd431fd653d7a9/src/main/java/jrm/webui/client/ui/Dir2DatPanel.java#L204), and again it's wrong for just one stupid copied string id :-/

**Comment by docbobo** [comment]
Okay, I believe you are saying that I quoted the wrong code, but the actual code for my case still produces the same result. 

Am I waiting for 2.5.2 or 3.0.0 now? 😉

**Comment by optyfr** [comment]
il will be fixed in 3.0.0
