### ISSUE TITLE
Size, CRC, MD5, SHA-1... missing

### ISSUE THREAD

**Issue by DocMAX** [optyfr/JRomManager#173]
Is this a bug? I am using v2.51 and OpenJDK 18.

![grafik](https://user-images.githubusercontent.com/5351323/174509277-2d418976-1cf2-4f8a-a821-6fea0ad3bfb3.png)

**Comment by DocMAX** [comment]
Seems the problem begins with v2.5.0 beta 5 ... also tried 3.0.0 - same issue.

**Comment by optyfr** [comment]
which dat file?
maybe a cache problem <= please try clear cache from context menu in profile list before loading the profile again
cache may be incompatible between JRomManager versions, it _could_ also happen when switching between JDK versions (cache are java serialized objects)

**Comment by DocMAX** [comment]
I created a .dat file with mame.exe (0.244). Drop cache did not help. Tried differend OpenJDK versions (17 Microsoft, 18) and always cleared cache.

**Comment by optyfr** [comment]
The problem is in swing version only, which is deprecated in v3.0.0 in favor of a jfx version
