### ISSUE TITLE
Missing Samples?

### ISSUE THREAD

**Issue by DocMAX** [optyfr/JRomManager#174]
I don't understand why missing? They are in my Source dirs!
![grafik](https://user-images.githubusercontent.com/5351323/174562198-cde1c399-fcf0-48e3-84fd-238287ba08b3.png)

**Comment by DocMAX** [comment]
Aha, it's not sorting them. They are detected if i put them to the destination dir.

**Comment by optyfr** [comment]
not sure to understand what happened there...

**Comment by DocMAX** [comment]
never mind for now..
