### ISSUE TITLE
Progression Window 32 Threads

### ISSUE THREAD

**Issue by DocMAX** [optyfr/JRomManager#175]
I have a 32 Threads CPU which fills the windows more than it can display. Can you optimize the GUI?

**Comment by optyfr** [comment]
swing version? possible that the 3.0.0 javafx version is already compliant... But still working on 3.0.0

**Comment by optyfr** [comment]
should be ok in javafx and smartclient versions for 3.0.0

**Comment by DocMAX** [comment]
What do you mean? I allready compiled 3.0.0 and see no difference.

**Comment by optyfr** [comment]
There is a vertical scrollbar in javafx and smartclient gui
Please try with 3.0.0 beta 1 then send me a screenshot if there is still a problem
