### ISSUE TITLE
v3.0.0-beta.1 (AppImage): cannot load Linux MAME XML

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#178]
I cannot load the file generated with `$ mame -listxml > mame_linux.xml`, double-clicking the Imported DAT does nothing.
It works if using the [official XML from MAME website](https://github.com/mamedev/mame/releases/download/mame0245/mame0245lx.zip).

**Comment by optyfr** [comment]
Sorry for the delay... Need to take a pause, my old PC has been monopolized by my wife, and only got a new one recently... I've not yet all rebuilt on my new PC and specifically I've still Linux env to be done (may need to add storage so it will take time and money), but I just tested with an extract using mame windows and it loaded perfectly, it may be access right related? did you get something in the logs?

**Comment by cinnamonmatexfce** [comment]
Welcome back @optyfr !! No need to be sorry 😊 Rather, it's good to know everything's fine! 🤟 
Women and wives are definitely much more powerful than us, what do you expect?! 😜
I'll try to gather logs as soon as I can... Meanwhile I'm asking you: what steps do you want me to follow in order to provide needed feedbacks?
What do you mean with: << *it may be access right related?* >>

<br>

Last thing, I dont' understand [this WARNING](https://github.com/optyfr/JRomManager/releases/tag/3.0.0-beta.1):

>Warning : No desktop gui for noarch/all/zip builds since javafx is hardware/os dependent, you'll have to use arch specific packages/installers, for uncommon os/hardware it'll be web or cli mode

Can I compile `v3.0.0-beta.1` from sources or not? (I'm on ArchLinux)

**Comment by optyfr** [comment]
If you find something suspect in the log, just attach it here

I think about access rights because appimages are sometimes awful with that, if you umask restrict access to other it's possible than the app can't simply read the file, but it's just a guess at this state
btw I don't even know the mame version you used, maybe it's mame version specific?

About the warning : javafx has native libraries ans so different jar files according os/arch so I can't make a "universal" rpm/deb/zip with javafx in it, but since you are under Archlinux that shouldn't be a problem, you should be able to build from source, at last manually, with no problem and get the javafx zip, but it may need some adjustment to do a working PKGBUILD anyway

**Comment by cinnamonmatexfce** [comment]
> btw I don't even know the mame version you used, maybe it's mame version specific?
> 

If you click the link it will point you to the release I tested at the time

**Comment by optyfr** [comment]
ok just tried with mame 245, everything is fine here

**Comment by optyfr** [comment]
installed a fresh minimal archlinux
seems that the image is totally wrong, I don't see any text in interface, so I suppose ressources are missing

**Comment by optyfr** [comment]
correction : this appimage does work under debian, it shows all texts, I also load a xml generated with the old bundled mame 0.238 without problem
I don't know why it shows no text with archlinux, maybe more a police display problem than missing text 
Can you send me a screenshot for comparison?

**Comment by cinnamonmatexfce** [comment]
>  Can you send me a screenshot for comparison?

![JRomManager-3 0 0-x86_64 AppImage](https://user-images.githubusercontent.com/65762930/214934776-4137e61b-aac0-4ec4-9b34-4c6f2cca73e1.png)

It just... Works... 🤔

**Comment by optyfr** [comment]
OK found out after a lot of googling : `ttf-ms-fonts` aur package is  needed for javafx :-/

**Comment by cinnamonmatexfce** [comment]
> `ttf-ms-fonts` aur package is needed for javafx :-/
>

Mmm... Strange...
I do have `extra/java17-openjfx 17.0.5.u1-1` installed, but `ttf-ms-fonts` is NOT!
