### ISSUE TITLE
Missing (?) gradlew build script in `JRomManager-3.0.0.zip` asset

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#184]
you should be able to build from source, at last manually, with no problem

_Originally posted by @optyfr in https://github.com/optyfr/JRomManager/issues/178#issuecomment-1404875589_
            

Where's the `build` script?
I cannot find it inside the [ZIP](https://github.com/optyfr/JRomManager/releases/download/3.0.0-beta.1/JRomManager-3.0.0.zip) asset (NOT the `Source code (zip)` one)

**Comment by optyfr** [comment]
from release note :

> - src archive is removed, to compile from sources => git clone --recursive https://github.com/optyfr/JRomManager.git

That involve to have git command and package management to handle this directly, but this shouldn't be a problem

**Comment by cinnamonmatexfce** [comment]
> from release note :
> 
> > * src archive is removed, to compile from sources => git clone --recursive https://github.com/optyfr/JRomManager.git
> 

I totally missed that part! OK, thanks.
