### ISSUE TITLE
Erratic behavior after killing the application, stops fixing early

### ISSUE THREAD

**Issue by juan-fuentes-sis** [optyfr/JRomManager#189]
Removing leftover files on the temp folder before starting it again solves the problem.

**Comment by optyfr** [comment]
ok, I need the version, the log files (to know why it stops fixing), some things were broken in 2.5, but if it's in 3.0 then that need to be fixed immediately

**Comment by juan-fuentes-sis** [comment]
Latest 2.5.x , I was worried 3 was not stable.

**Comment by optyfr** [comment]
I probably fixed the problem then... ;-)
