### ISSUE TITLE
Synology Package

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#19]
Hi optyfr, I hope you're fine.

A Synology package would be awesome since JRomManager can be used via Webbrowser in Server mode.
I've also requested this here https://github.com/SynoCommunity/spksrc/issues/3706 and thought you could provide some help.

Thanks

**Comment by optyfr** [comment]
Since I don't own any synology product, a maintainer is needed

**Comment by optyfr** [comment]
Seems that there is no feedback from synology community, and since I don't if it's even doable regarding software and hardware requirement, I will close. Don't hesitate to reopen, if you get news from synology community
