### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by juan-fuentes-sis** [optyfr/JRomManager#190]
JRomManager is probably the best open-source software to manage roms available.

Sadly I couldn't find any public Discord or IRC channel.

It would be particularly interesting, specially since its open source nature allow people with Java experience in data Management software (Me for example) to chat and maybe contribute.

**Comment by optyfr** [comment]
Well... TBH, I'm not so convinced about the JRomManager community size, at least not to feel the need of a discord server... Maybe I'm wrong, I don't know, I'm not against but just need to be convinced that it won't be for only 2 or 3 peoples  
BTW did you see that there is a "Discussion" page on GitHub? That not really like a chat app, but that should avoid to open issues just to ask or suggest things

**Comment by juan-fuentes-sis** [comment]
Ok, I will have a look.
