### ISSUE TITLE
CRC matching case sensitive

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#2]
Almost all my ROMs show as "found, but is incomplete and not fully fixable" after a scan.
It seems that CRC matching is case sensitive, because all affected ROMs got characters in their checksum and have errors like "has wrong CRC (got c8cdb4ed vs C8CDB4ED)".
(Occured with various No-Intro DATs on Arch Linux ...)

**Comment by optyfr** [comment]
Ok, will fix that asap

**Comment by optyfr** [comment]
Fixed in commit [25207062b30e9df32600da3867432fdd98f4365e](https://github.com/optyfr/JRomManager/commit/25207062b30e9df32600da3867432fdd98f4365e)
