### ISSUE TITLE
RV7z instead of torrent7z

### ISSUE THREAD

**Issue by freitagdavid** [optyfr/JRomManager#20]
So I just wanted to make a quick suggestion. Though the spec is not available yet it should be soon the if you haven't been keeping up with the progress of RomVault 3 creator of RomVault has created a new alternative to torrent7zip for the new version of RomVault I have a strong feeling that this will beat out torrent7zip in popularity owing to the fact that from what I've seen the development on torrent7zip has completely halted, and romvault is such a popular manager. From my use so far it does seem to be working quite well and doesn't throw the extra data errors like torrent7zip does. Just something I figured I would put out there. Great work on the rom manager it really is a huge problem that no truly cross platform managers existed. I'm personally looking at making my own but that project is on the back burner I'm happy your making something I can use in the meantime on both my windows, and linux machines.

**Comment by freitagdavid** [comment]
I actually thought of possibly a preferable option. Instead worrying about implementing all of these different compressors your could just allow the use of arbitrary compression binaries by doing something along the lines of have a couple fields where you tell the manager where the binary is, and then tell it was command corresponds to each function eg. extract, compress, delete, add, etc. Not sure if this would be feasible another option though it wouldn't possibly help me much since I don't know java would be to add a nice compressor api so people could easily write plugins.

**Comment by optyfr** [comment]
Believe me, calling an external command to check validity on ten thousand 7z files will result in very slow processing, whatever the language and os used, that’s why tzip has been ported and integrated in ... on the other hand I don’t believe in success of a t7z reimplementation in an era where disk space costs nothing (and won’t see it for sure officially back on some well known private trackers)
So let’s say that it will be implemented only if widely used
