### ISSUE TITLE
[JRomManager3] Merge mode (and maybe more) broken after jlink phase (when packaged)

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#203]
Exported XML of filtered sets (**CHD Required**) via M. A. M. E. UI interface (by pressing `ALT+E`), see attachment.

JRomManager3 (AppImage) seems not to recognize any machines at all when Scanning the attached XML.
After the *Scan* operation (I think it's actually doing nothing, since it only lasts very few seconds), *Report* comes up but it shows **zero machines**.

Latest stable (2.5.1, [installed from AUR](https://aur.archlinux.org/packages/jrommanager-bin)) works fine.
____________________________________________________________________________________________________________________________________________
Attachments:

[CHD_sets_XML_exported.zip](https://github.com/optyfr/JRomManager/files/11181602/CHD_sets_XML_exported.zip)

![M  A  M  E  - System Filter - CHD Required](https://user-images.githubusercontent.com/65762930/230679875-35abe953-a7ef-41bf-9a55-d0ea5638aff8.png)

**Comment by optyfr** [comment]
Did a first try with dev build and it worked ok, will try next with the appimage
Is there something to fix with 2.5.1? are you sure about your settings? don't hesitate to play with context menu in report to see if something is prefiltered (we don't show "ok" machines by default)

**Comment by optyfr** [comment]
The appimage worked ok for me with your xml

**Comment by optyfr** [comment]
I may have found something, can you confirm that you use merged mode? and if yes, can you try with split mode and tell me if report is empty or not?

**Comment by cinnamonmatexfce** [comment]
- *Roms Dest.* > `/SOMEPATH/mame_c`
- *Disks Dest.* > `/SOMEPATH/mame_c`
- *Samples Dest.* > `/SOMEPATH/mame_c_s`
- *Src Dir.* > `/SOMEPATH/rom_tobe_FIXED`

</br>

- `Enable Multithreading`
- `Create missing sets`
- `Use implicit merge`
- `Zip archive`
- `Merged (no BIOS)`
    - `All clones even if no collision`

</br>

- *Threading* > `16`
- *Compressors* >
    - 	*Zip* > `ULTRA`
    - 	*Zip (external)* > `ULTRA` ; `Threads = 1`
    - 	*7z (external)* > `ULTRA` ; `Threads = 1` ; `Solid archive = FALSE`

</br>

Please have a look at the ZIP attachment with logs+screenshots.
Pay attention at the bottom-left side of the *Report*'s window and check the differences between `2.5.1` and `3.0.0.b5`.

______________________________________________________________________________________________________________________________________


[JRomManager_logs_ScreenShots.zip](https://github.com/optyfr/JRomManager/files/11183232/JRomManager_logs_ScreenShots.zip)

**Comment by cinnamonmatexfce** [comment]
> can you confirm that you use merged mode? 

Yup! You're a damn genius!!

</br>

> can you try with split mode and tell me if report is empty or not?

*Split* mode works fine indeed! ;)

**Comment by optyfr** [comment]
Strangely, It works outside packaging under eclipse, then it doesn't work after packaging...

**Comment by optyfr** [comment]
a dependency was missing, please try [3.0.0-beta.6](https://github.com/optyfr/JRomManager/releases/tag/3.0.0-beta.6), and reopen if it still fails

**Comment by cinnamonmatexfce** [comment]
> a dependency was missing, please try [3.0.0-beta.6](https://github.com/optyfr/JRomManager/releases/tag/3.0.0-beta.6)

Thank you dear! ;)
