### ISSUE TITLE
fixing (unneeded) will led to incomplete sets

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#208]
Using **full** unmerged (including BIOS and DEVICE).

After fixing operations, some sets will be marked as incomplete.
After manually creating the zips of the above sets, a Scan operation will report roms inside that sets as unneeded.

Also, *Report* has found 45459 sets VS 45476 of M. A. M. E.'s XML.

![JRomManager3 0 0 b7_AppImage_incomplete_sets](https://user-images.githubusercontent.com/65762930/232309427-b081df76-7725-4e2a-9d9f-930d5e04bd96.png)

**Comment by optyfr** [comment]
ok, I will need the mame xml file and the jrm settings file, I will try to reproduce from this...

**Comment by cinnamonmatexfce** [comment]
M. A. M. E.'s XML is taken from Windows' `mame.exe -listxml > listxml.xml` (`0.253` at the time of writing).

______________________________________________________________________________________________________________________________________

[JRomManager-3.0.0-beta7-x86_64.AppImage - logs.zip](https://github.com/optyfr/JRomManager/files/11255397/JRomManager-3.0.0-beta7-x86_64.AppImage.-.logs.zip)

**Comment by optyfr** [comment]
Tried with an incomplete collection, it fixed all it can, then a rescan didn't show anything to fix again... I will try with a more complete one but this will take time...

**Comment by cinnamonmatexfce** [comment]
In the meanwhile I've also run into a **sha1** Scan. Nothing changed, sadly.

**Comment by optyfr** [comment]
Please DM me on discord

**Comment by optyfr** [comment]
fixed with #774d86574e4ffa0afda311a794ed9c43e6af0572

**Comment by optyfr** [comment]
the commit 774d86574e4ffa0afda311a794ed9c43e6af0572 solved the issue

**Comment by cinnamonmatexfce** [comment]
> the commit [774d865](https://github.com/optyfr/JRomManager/commit/774d86574e4ffa0afda311a794ed9c43e6af0572) solved the issue

[beta10](https://github.com/optyfr/JRomManager/releases/download/3.0.0-beta.10/JRomManager-3.0.0-x86_64.AppImage) solved this issue! Thank you @optyfr ! 😎
