### ISSUE TITLE
FeatReq: Add 'Copy' and 'Search on google'

### ISSUE THREAD

**Issue by RenHoekNL** [optyfr/JRomManager#22]
I love the program but I'd like it if in the various tables, I could copy fields to the clipboard, or even directly open a web browser looking for the value of the field. This would save me tons of time trying to find those few missing roms.

Thanks!

**Comment by optyfr** [comment]
OK, for copying into system clipboard (swingui and webui)
Now for opening directly a web page, while it can be easily done in the web version of the ui, I need at least to tell the browser where to search (for example, if I want to use google, it would be something like https://www.google.com/search?q=my%20field%20value), so what do you mean more precisely when talking about "looking for the value of the field"?

**Comment by RenHoekNL** [comment]
Exactly that.. For example if I right-click a name of a rom or the SHA1 hash of a rom, I want to option to spawn a web browser to https://www.google.com/search?q=thisgamexx.bin

**Comment by RenHoekNL** [comment]
Thank you! :)
