### ISSUE TITLE
Crea profile Problem

### ISSUE THREAD

**Issue by ilsaul** [optyfr/JRomManager#220]
Hi,
I downloaded the latest version 2.5.1 and tried to create a profile of mame 0.257
I use a Mac and have found some difficulty.
I tried to import Dat or Import Software List both with the same result.
In any case, after choosing one of the options, a window pops up asking you to choose an EXE or DAT file to import.
As far as I know the Dat format has been abandoned in favor of the Xml format but maybe you keep it for backwards compatibility but the xml should also be added.
EXE in Mac doesn't exist but I think executable mame (without extension) is bane.
Starts another reading progress window telling you to read the lines. After a while he ends up telling me to choose a file. I have a doubt here but shouldn't you create a profile for me? i was expecting a save dialog not an open file but ok then i create an empty file with extension dat and choose it. And the profile is created.
But I have some doubts the profile doesn't say the version and the sets, roms and disks are zero of zero.
To try, I go to scan, insert where the roms are and a source folder with some roms inside and run the process which ends in 1 second and the report shows 0 found.
What did I do wrong?

Thank you

**Comment by cinnamonmatexfce** [comment]
`mame -listxml > mame.xml` and then you load up that file.

There's `beta-11` available, btw

**Comment by ilsaul** [comment]
Hello, the new version 3 is more beautiful. This version works in my case. Thank you
