### ISSUE TITLE
export only some categories?

### ISSUE THREAD

**Issue by kintaro1981** [optyfr/JRomManager#228]
Is it possible with JRomManager 2.5.1 to filter Mame roms excluding some categories (for example pachinco, adults, recent games, ecc) and exporting them?

I would like to trim down the whole collection excluding some categories.

**Comment by cinnamonmatexfce** [comment]
Not on computer, ATM.
Please, have a look at here: https://github.com/optyfr/JRomManager/wiki/Scanner#advanced-filters

Oh, install latest beta (v11).
