### ISSUE TITLE
Not working on M2 Mac

### ISSUE THREAD

**Issue by yatiac** [optyfr/JRomManager#229]
I am trying to run the latest beta version and I am getting this error: 
<img width="293" alt="image" src="https://github.com/optyfr/JRomManager/assets/1914303/b5e68301-106f-4411-bf85-6142fc3fd325">

I also tried with the latest stable version and got the same:
<img width="273" alt="image" src="https://github.com/optyfr/JRomManager/assets/1914303/6f7589fd-20a3-4e10-afc2-0b93dded4dc7">

I might be doing something wrong but I don't know what. My Java version is 17: 
<img width="644" alt="image" src="https://github.com/optyfr/JRomManager/assets/1914303/5bf1c243-8076-4661-8b46-ba81036a692a">

**Comment by optyfr** [comment]
Hello, no idea, I can’t test since I don’t have a mac, it has previously been reported to work…
Probably need to wait for another mac user help…

**Comment by jmr224** [comment]
@yatiac 

I had the same problem  running Mac Ventura on intel Mac but as I say has the same error, this worked for me, make sure that you've dropped JRom in to applications  

Solution:
Disable gatekeeper for the application by doing eh following :

Open terminal and enter this line:

sudo spctl --master-disable

Also enter this line:
xattr -cr /Applications/JRomManager.app

**Comment by optyfr** [comment]
Closing since there has not benn feedback on  the proposed solution by @jmr224 
Furthermore image is now built with Java 21
