### ISSUE TITLE
[Request] Compression: Files (None)

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#24]
Please add a feature allowing to scan / fix uncompressed ROMs which are not stored in parent folders.

Motivation: For some single file systems (e.g. Game Boy) I'd rather like to store ROMs uncompressed without subfolders.

**Comment by optyfr** [comment]
Fixed in 2eacf3456597839cc2b5c698a842f6d6cdacc062
Will be available in next release
