### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by ghost** [optyfr/JRomManager#249]
Hi

Dutch is my native language and I also speak English, so I want to translate the program to Dutch.
However I'm not a programmer, can't read code and can't compile the program.

Is there a way I can translate this program to Dutch without this knowledge? (I don't want to learn compile)

Thanks
Lisa

**Comment by optyfr** [comment]
Yes, it's totally possible, the english file to translate is [here](https://raw.githubusercontent.com/optyfr/JRomManager/master/jrmcore/src/main/resources/jrm/resources/Messages.properties)
When it's translated, I can reintegrate in project and the translation will be available at next release

**Comment by girlblender** [comment]
FUCK YOU LOSER
