### ISSUE TITLE
3.0.0-beta not deleting unneeded items from output

### ISSUE THREAD

**Issue by tpmoney** [optyfr/JRomManager#257]
Unselected items show as "unneeded" in the report after a scan, but the Fix button is disabled. I don't have any of the "Ignore..." settings enabled in the main settings tab. If I have other items to do (like adding missing items) the fix button is enabled and the missing items are added, but the unneeded items remain.

If I'm reading the code correctly, it's possible that there is inverted logic surrounding deleted items. In the 3.0.0-beta.20 tagged release, it looks like an item is put into the report as unneeded here:

https://github.com/optyfr/JRomManager/blob/4532efb50bc74fe20b3a869d73c42aa7c73ef015/jrmcore/src/main/java/jrm/profile/scan/Scan.java#L1850C4-L1856C5
```
                        if (!(mergeMode.isMerge() && ware.isClone()))
                        {
                                if (!missingSet)
                                        reportSubject.setUnneeded();
                                else
                                        reportSubject.setFound();
                        }
```

Then a few lines later, after it's determined that the `ignoreUnneededContainers` flag isn't set, the `remove*` methods are called:

https://github.com/optyfr/JRomManager/blob/4532efb50bc74fe20b3a869d73c42aa7c73ef015/jrmcore/src/main/java/jrm/profile/scan/Scan.java#L1861C3-L1865C4
```                if (!ignoreUnneededContainers)
                {
                        removeUnneededClone(ware, disks, roms);
                        removeOtherFormats(ware);
                }
```

But inside those methods, the logic used to add the item to the report as unneeded (`if (!(mergeMode.isMerge() && ware.isClone()))`) appears to be inverted when deciding whether to add it to the list of items to be deleted:

https://github.com/optyfr/JRomManager/blob/4532efb50bc74fe20b3a869d73c42aa7c73ef015/jrmcore/src/main/java/jrm/profile/scan/Scan.java#L903C3-L903C45
```
                if (mergeMode.isMerge() && ware.isClone())
```

If I'm reading things right, unneeded items are never added to the list of actions, so that's why the Fix button remains disabled and why fixes when there are other actions available don't delete the items.

**Comment by optyfr** [comment]
Wanted to look at it today, but sorry, that's is not totally clear to me : I need to know exactly what is reported as unneeded but not removed, is it entire clones containers, or just some roms or discs inside a set ? Furthermore I need to know what was exactly the scanner settings (screenshots)
There is probably a problem, no doubt on it, but there are separate cases and it depends if it's in merge mode and if it happens in clones, and theres is differentiation if it's roms or if it's disks, if it's in archive, or in folders, etc...
Maybe knowing the dat may help too

**Comment by tpmoney** [comment]
Alright I'll see if I can give an example here. Using this DAT file: 
[MAME 0.263 (arcade).dat.zip](https://github.com/optyfr/JRomManager/files/14625847/MAME.0.263.arcade.dat.zip)

And these settings:

<img width="805" alt="Screenshot 2024-03-16 at 21 54 29" src="https://github.com/optyfr/JRomManager/assets/4555240/8f6b0f56-874f-4ea0-ad25-50a33cb9b134">

And these filters:

<img width="331" alt="Screenshot 2024-03-16 at 21 54 48" src="https://github.com/optyfr/JRomManager/assets/4555240/6d7df788-e1ba-4aa2-a2f8-c68f811e3129">

That will generate a set and profile that includes `005` and will place a file `005.zip` into the output dir:

<img width="799" alt="Screenshot 2024-03-16 at 21 56 50" src="https://github.com/optyfr/JRomManager/assets/4555240/2aac3447-7370-4304-9739-9f85601503e1">

<img width="779" alt="Screenshot 2024-03-16 at 21 58 04" src="https://github.com/optyfr/JRomManager/assets/4555240/1496624e-2761-4205-ad4c-cd6e40ece709">

If I then unselect 005 from the profile and scan and report again, the report declares 005 as "Unneeded":

<img width="812" alt="Screenshot 2024-03-16 at 21 59 29" src="https://github.com/optyfr/JRomManager/assets/4555240/880b3098-902a-4965-926b-27996e1b331f">

But despite that, the `Fix` button remains greyed out and 005.zip stays in the output directory. And this applies for any unselected game. I should note to that despite having "include clones" I've unselected all the clones for game except very specific ones, so it doesn't appear to be getting kept because a clone relies on it. Likewise it occurred to me that I was using the split output and that I should check other outputs so I chose both `non-merged (no bios)` and `merged (no bios)` output options as well, with 005 still unselected and while it was reported as "unneeded" every time, and I could run the `Fix` button to do the conversion between the different outputs, 005.zip remained behind every time.

Hopefully that gives you everything you need for this, but if not let me know and I'll get you more. I can also get you the settings export file if that will help for both with and without the game selected.

**Comment by optyfr** [comment]
Thank you, I will look at this later today
