### ISSUE TITLE
Samples is subdirectories don't appear to be scanned in new beta

### ISSUE THREAD

**Issue by tpmoney** [optyfr/JRomManager#258]
In the 3.0.0-beta.20 release if the "samples" are in a sub directory (e.g. `MAME_Extras/samples/${sample}.zip`, it doesn't look like the scanner is finding them if I only include `MAME_Extras/` as a source dir. If I include MAME_Extras/samples/ then it does find them properly.

**Comment by optyfr** [comment]
It depends of the dat, mame extras can be problematic depending on how dat is made, does it needs to go into each sample archives or is each zip taken as single "rom file" in the dat and sample dir is the container ? in other words I need the dat used to check if something is wrong or not. Dir scanner is tied with container > entries and result may vary according scan depth

**Comment by tpmoney** [comment]
I'm using the MAME 0.236 (arcade).dat from Progetto. I've attached a copy here. I've also added a screenshot of how the dirs for the profile are setup. Without the last source entry, the samples aren't found.
[MAME 0.263 (arcade).dat.zip](https://github.com/optyfr/JRomManager/files/14625837/MAME.0.263.arcade.dat.zip)
<img width="660" alt="Screenshot 2024-03-16 at 21 50 19" src="https://github.com/optyfr/JRomManager/assets/4555240/ea5ec1ec-0747-441e-b435-d1676cba828e">
