### ISSUE TITLE
JRomManager crashes attempting to "Import Dat" with MAME 0.174

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#26]
Hey optyfr!
As in title.
I tried with both mame executable parsing and XML generated file from `mame -listxml > mame0174.xml`.
After some seconds JRomManager prints out various `Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException` in bash output.

I'm using: https://aur.archlinux.org/packages/jrommanager-bin/
And JAVA is set to:
>`$ archlinux-java status`
>`Available Java environments:`
> `java-13-openjdk (default)`

Here's to you: bash output, log and screenshot.
[jrommanager_bash_output.log](https://github.com/optyfr/JRomManager/files/4674464/jrommanager_bash_output.log)
[JRM.0.log](https://github.com/optyfr/JRomManager/files/4674465/JRM.0.log)
![JRomManager_failedprofileloader_mame0174](https://user-images.githubusercontent.com/65762930/82765678-12807180-9e19-11ea-874d-a18626e9c67e.jpeg)

**Comment by optyfr** [comment]
Hello,
Can you attach the xml generated dat file?
Thank you

**Comment by cinnamonmatexfce** [comment]
JRomManager crashes also on Winddows 10, same way: both exe parsing and generated `mame -listxml`
[listxml0174.zip](https://github.com/optyfr/JRomManager/files/4675622/listxml0174.zip)
[mame0174exe.zip](https://github.com/optyfr/JRomManager/files/4675642/mame0174exe.zip)

**Comment by cinnamonmatexfce** [comment]
> Hello,
> Can you attach the xml generated dat file?
> Thank you

[mame0174exe.zip](https://github.com/optyfr/JRomManager/files/4675649/mame0174exe.zip)
[listxml0174.zip](https://github.com/optyfr/JRomManager/files/4675648/listxml0174.zip)

JRomManager crashes also on Winddows 10, same way: both exe parsing and generated `mame -listxml`

**Comment by optyfr** [comment]
Found it! encountered 0xff800000 hex number for rom offset value, which can't be parsed into a signed 32bit value (int) and need to use 64bit (long)
Will be in release 2.4 (soon)

**Comment by cinnamonmatexfce** [comment]
> Found it! encountered 0xff800000 hex number for rom offset value, which can't be parsed into a signed 32bit value (int) and need to use 64bit (long)
> Will be in release 2.4 (soon)

Can't wait for 2.4!!! :p 
Again, many many thanks @optyfr!!!

**Comment by cinnamonmatexfce** [comment]
Hey optyfr, I'm adding you another DAT (M. A. M. E. 0.37b5) that crashes JRomManager when importing. Could you please see it and check if it's fixable? Thanks!
[mame037b5_2nd.xml.zip](https://github.com/optyfr/JRomManager/files/5360254/mame037b5_2nd.xml.zip)
