### ISSUE TITLE
Log Level preference has wrong text label

### ISSUE THREAD

**Issue by tpmoney** [optyfr/JRomManager#272]
The preference for changing the log level is labeled "Threading" in v3.0.2

<img width="831" alt="Screenshot 2024-04-10 at 22 54 08" src="https://github.com/optyfr/JRomManager/assets/4555240/c460a48d-eb81-4c52-8592-932ec8412929">

**Comment by optyfr** [comment]
Problem reside in english resource file, french version is ok :shrug:
