### ISSUE TITLE
Task :JRomManager:javadoc FAILED

### ISSUE THREAD

**Issue by fixxOrz** [optyfr/JRomManager#28]
I tried installing on Linux Mint 19.3 according to the instructions and got the following error message:

```
> Task :JRomManager:javadoc FAILED
Unable to find the 'javadoc' executable. Tried the java home: /usr/lib/jvm/java-11-openjdk-amd64 and the PATH. We will assume the executable can be ran in the current working folder.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':JRomManager:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/cjspizz/Downloads/JRomManager-2.3.0-src/JRomManager/build/tmp/javadoc/javadoc.options'

...

BUILD FAILED in 13m 58s
47 actionable tasks: 47 executed
```

**Comment by optyfr** [comment]
The message is telling you that the « javadoc » executable is missing... so your current openjdk installation seems incomplete 
Btw since your linux is debian based you should try this : 
https://github.com/optyfr/jrommanager-debian

**Comment by fixxOrz** [comment]
Thanks for the reply. I'm on Ubuntu Bionic Beaver, so I chose the Jessie version of Deb but got this message:

> Unable to locate package jrommanager

Instead, I downloaded the .deb package from https://github.com/optyfr/JRomManager/releases/tag/2.3.0, and that installed.

UPDATE: I also see it's available as a Flatpak. I think it would be helpful to include these simpler options in the README install instructions. I've been dying for a rom manager for linux, and what you've built seems awesome and getting high marks on the PD forum—thank you!!!

**Comment by optyfr** [comment]
If the debian repository is correctly installed that type of message should never happen
Did you type « apt update » before trying?
You can also download and install the deb package available from the github’s release directory no need of flatpak

**Comment by fixxOrz** [comment]
> If the debian repository is correctly installed that type of message should never happen
> Did you type « apt update » before trying?

Yes.

> You can also download and install the deb package available from the github’s release directory no need of flatpak

That's what I ended up doing.

**Comment by optyfr** [comment]
Installed Linux Mint 19.3 in a VM :
- javadoc is available, just installed default-jdk package using the Linux Mint's Software Manager
- jrommanager-debian repository worked fine (but you have to be root when typing commands to install repository and install), I used buster, but anything should work since packages are the same between jessie, stretch, and buster
