### ISSUE TITLE
[REQUEST] Adding a check to still create needed files for complete set, despite filters (nplayers.ini AND catver.ini) rules

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#32]
Hey optyfr!
Let's say I'm filtering MAME romset using `catver.ini` and `nplayers.ini` via [Advanced filters]...
I'll uncheck all categories I don't need, eg: `Casino`, `Electromechanical`, `Tabletop`, `Telephone`, `Workstation`
And, from nplayers.ini, also, eg: `BIOS`, `DEvice`, `Device`, `5P alt`,  `6P alt`
Also, I'll uncheck `MECHANICAL` inside [Filters].
Then, for example JRomManager won't create `neogeo.zip` as it falls into `neogeo=Multi-cart Board` because of filtering.
Ok, this is what exactly I asked to; but in reality inside the romset there are games which `neogeo.zip` is howevere needed (see Metal Slug games).
So...
Will you consider adding a check to force creation of needed BIOS and/or DEVICES (despite filtering selections) _only if a game (**that need its BIOS and/or DEVICE**) has been added into the romset during [Fix] operation_?

**Comment by optyfr** [comment]
Hello,
"Multi-cart Board" is a sub-category of what category? I have a catver.ini but there was no "Workstation" category... And what happen if you deselect the category from what depend "Multi-cart Board" then select back only "Multi-car Board"?

**Comment by cinnamonmatexfce** [comment]
Sorry, actually turns out I **de**-selected also `BIOS` `DEvice` `Device` from `nplayers.ini`!!!
Btw, could you still add that checker? Is doable?

**Comment by optyfr** [comment]
If you need bios, simply keep checked BIOS (in general, un-checking this entry in nplayers.ini list is a bad idea, but this entry is there and I can't control it), if you don't wan't incomplete games created just because of bios, check "create only complete set" in settings
