### ISSUE TITLE
2.4.3 doesn't build/fix on Windows 10.

### ISSUE THREAD

**Issue by Noisecommander** [optyfr/JRomManager#35]
Hey there,

v2.4.3 doesn't seem to want to build or fix romsets on my PC at all.
I have tested this with a couple different dats.
I'm running Windows 10 x64 v2004 with Oracle JRE build 1.8.0_251-b08.

1. I start with a clean JRomManager (either msi install outside a protected dir or portable version, and removed .jrommanager in my profile).

2. Add and load datfile.

3. Either change compression & merge mode settings or not.

4. Add empty dirs for ROMs and samples, or point to existing dirs that needs fixing.

5. Add source files.

6. Scan.

7a. When building a new romset I get a complete report but I can't fix.
7b. When fixing an existing romset I get a complete report and sometimes a fix button but nothing seems to change when I press fix and the fix butting just stays lit.

I have tested 2.4.2 as well and everything seems to work as expected on that version.

**Comment by optyfr** [comment]
2.4.3 was compiled for java 8 but with jdk 11, and that seems to lead to compatibility problems, at least typecasting problems between java.nio.Buffer and java.nio.ByteBuffer
While searching for a fix, this should work as is if you install java 11 or more as the default jvm
btw  2.5.x will definitely require at least java 11 or more

**Comment by Noisecommander** [comment]
It took some time to research about the state of JRE's in Windows, but everything seems to be working as intended running AdoptOpenJDK 14 with HotSpot.

**Comment by optyfr** [comment]
fixed with commit e203ca6e5f626f8ece0b12dbfac234c180cc7569
