### ISSUE TITLE
Can't run JRM from CLI

### ISSUE THREAD

**Issue by fixxOrz** [optyfr/JRomManager#37]
I am trying to cobble together a linux bash script to automate as much of the retrieval of updates (including the proper dats and torrent files for the new full sets), the actual updating of the sets, then joining the swarm. I've been using the JRomManager GUI to do this manually. For the bash scripts to function, I a cli program. I went to the JRM wiki's [CLI mode page](https://github.com/optyfr/JRomManager/wiki/CLI-mode#Cli-mode) to get the info I needed, or so I thought.

The instructions state:

> usage: _java -jar JRomManagerCLI-2.2.0.jar [args]_
> alternative usage: _java -cp JRomManager.jar jrm.JRomManagerCLI [args]_
> args:
>  -f,--file Input file
>  -i,--interactive Interactive shell
>  If no args, take commands from standard input (or pipe)

But, if I run "java -jar JRomManagerCLI-2.2.0.jar -i" I get the error "Unable to access jarfile JRomManagerCLI-2.2.0.jar."

I searched my system for "JRomManagerCLI-2.2.0.jar" but found nothing. I opened up the installed files list and found /opt/jrommanager/lib/jrm-jrmcli-2.4.4.jar.

Thinking the wiki likely just needs updating, I tried using "java -jar /opt/jrommanager/lib/jrm-jrmcli-2.4.4.jar -i" but get the error "no main manifest attribute, in /opt/jrommanager/lib/jrm-jrmcli-2.4.4.jar."

Can JRM still be run from the command line? if so, how?

**Comment by optyfr** [comment]
The JRomManagerCLI jar is a separate download available in release section of my github repos (it is not included into the deb package)...
Now you can also use the classic JRomManager.jar from the deb package but you must use the alternative syntax, you may have to cd in the JRomManager install path

**Comment by fixxOrz** [comment]
Got it. Thanks!
