### ISSUE TITLE
[Feature Request] Ability to create textual reports

### ISSUE THREAD

**Issue by RibShark** [optyfr/JRomManager#38]
I would like the ability to create textual reports of a scan, similar to those produced by ClrMamePro. These can be distributed with sets as further proof of their completeness.

**Comment by optyfr** [comment]
Humm, did you look in the reports folder? There is two types of report files, the binary one (a serialized java file, \*.report), and the textual report file (\*.log)

**Comment by RibShark** [comment]
Ah, wasn't aware that it saved them there, thanks!
