### ISSUE TITLE
[REQUEST] storing / using cache in Scanner for also uncompressed (Directories) sets

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#44]
```
JRomManager 2.5.0 BETA, rel. 2
```
As in title.
If working with uncompressed romsets, I found that Scanner will always full scan again and again as if it were the first time.

Would be nice to add - during the first Scan - a sort of timestamp to the uncompressed files so, if they won't change, cache kill keep stored information, thus making subsequent scans fast to re-check!

**Comment by optyfr** [comment]
I don't forget you, but I need to find time to work on JRomManager, and that's not very easy at the moment...

**Comment by cinnamonmatexfce** [comment]
Hey @optyfr! No problem, thanks!

**Comment by optyfr** [comment]
Should be fixed in latest commit, need to test it a little more, it will be available in 2.5.0 beta 3
