### ISSUE TITLE
[REQUEST] Batch Configure Profiles

### ISSUE THREAD

**Issue by RibShark** [optyfr/JRomManager#47]
To save a lot of time, it would be nice if we could batch configure our profiles. For example, automatically set the roms dir to "A:\Specific\Directory\Profile Name\" and set the compression option for all profiles at once.

**Comment by cinnamonmatexfce** [comment]
Did you try "Import Settings" and "Export Settings"?

**Comment by optyfr** [comment]
Are you talking about the cli mode?

**Comment by optyfr** [comment]
No answer to this issue, not sure that it's really an issue, seems more to be a misunderstanding, so I close it, don't hesitate to reopen and argue if I'm wrong
