### ISSUE TITLE
Cannot change size of all collumns

### ISSUE THREAD

**Issue by mase76** [optyfr/JRomManager#5]
Hi!
I am not able to change the size of the right column next to "result" in the batch tools.
I only see "S...", and that it is a checkbox. What is this checkbox for?

**Comment by optyfr** [comment]
Hi
It is not resizable because it’s a checkbox, but you’re right: tooltips in header are missing so I will add those tooltips for v1.9
Now the purpose is for selecting the line in the batch processing, so that checked mean « include in dir update » and unchecked is « exclude from dir update »

**Comment by optyfr** [comment]
commit f57c284a2c98f74bef59c575b57f9ca6e9bc3ac8 close #5
