### ISSUE TITLE
Client-Server stucture

### ISSUE THREAD

**Issue by mase76** [optyfr/JRomManager#6]
Hi!
I think, a real killer-feature would be a client-server structure. Me, and I think many other users
have their roms on a headless nfs or samba share. At the moment processing the romsets
can take a very long time, because files are read from and written to the directories over the
network. If there were a headless server running on the server, where a graphical
client could connect to, it could really accellerate the processing.
What do you think? Maybe a feature for 2.0?

**Comment by optyfr** [comment]
Good idea! Now I hesitate between a full web frontend or a java gui client...

**Comment by optyfr** [comment]
Btw, keep in mind that all data processing logic will have to reside on server part (compression, decompression, checksuming, ...), so that your nfs server will need enough memory and cpu

**Comment by mase76** [comment]
Yes, but it would save much time. Processing of about 45GB took several hours. A large chd folder would take days.

**Comment by optyfr** [comment]
wow! are you over wifi?

**Comment by mase76** [comment]
From my notebook yes. But It could be, that I am holding it wrong.
I am new to these romset processing.
But you are right, a nice webui would make a ui client unnecessary.

**Comment by optyfr** [comment]
Wifi is 2 to 3 times slower than a wired connection, it is even slower with lot of small files (the problem here is latency and packet round trip, not bandwidth)
I’m now using JRomManager directly on the NAS thru VNC remote desktop because I do lot of scans again and again

**Comment by mase76** [comment]
My server is a headless Debian machine.

**Comment by optyfr** [comment]
Me too, you can have a remote desktop without having a screen connected or even a gfx card! desktop is then only accessible thru VNC remote protocol, you just have to install xfce4 package for a light WM, and tigervnc-server (you will have to configure it but there is a lot of tutorials about that on the net), then install tigervnc client on windows

**Comment by mase76** [comment]
I know, but I don't have a desktop installed. I want to keep it running in console only.

**Comment by optyfr** [comment]
Not sure to do that for 2.0, will have to release other new features before this big enhancement

**Comment by optyfr** [comment]
commmit 5e9bd19477ccdffb399f0a0cb055bf13363376fd close #6
