### ISSUE TITLE
Option to set the number of simultaneous file processes

### ISSUE THREAD

**Issue by mase76** [optyfr/JRomManager#7]
Hi!
Is the default to process 4 files simultaneous? That can be a problem when
working on a network share. I think, processing file by file on network shares is
a better idea.
Can you add an option to configure the number of simultaneous file processes?

**Comment by optyfr** [comment]
I suppose that you’re talking about the batch tool mode? Because otherwise you would have just to uncheck « enable multi threading »
For dir update batch it will be available in v1.9 via « custom settings » menu item, it is already capable but there is no way to choose in v1.8

**Comment by optyfr** [comment]
commit f57c284 close #5, close #7
